const AI_ENDPOINT="";let mode="unknown",file=null;const $=id=>document.getElementById(id);
document.querySelectorAll(".choice-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");mode=b.dataset.target});
$("photo").onchange=()=>{const f=$("photo").files?.[0];if(!f)return;file=f;const r=new FileReader();r.onload=e=>{$("preview").src=e.target.result;$("previewBox").classList.remove("hidden")};r.readAsDataURL(f)};
$("clear").onclick=()=>{$("photo").value="";file=null;$("previewBox").classList.add("hidden");$("result").classList.add("hidden")};
function demo(){if(mode==="bee")return{name:"🐝 蜂の可能性",candidate:"蜂（種類は写真だけでは確定できません）",risk:"注意",score:78,action:"近づかず、安全な場所から距離を取る",caution:"巣・集団がある場合は刺激せず、必要に応じて専門業者へ相談。",medical:false};if(mode==="tick")return{name:"🕷️ マダニの可能性",candidate:"マダニ（写真だけでは確定できません）",risk:"注意",score:74,action:"付着している場合は無理に引き抜かず、医療機関への相談を検討",caution:"皮膚への付着や刺咬が疑われる場合は自己判断で無理な処置をしない。",medical:true};return{name:"確認が必要",candidate:"蜂・マダニのどちらかを選んで再確認してください",risk:"判定困難",score:45,action:"近づかず、より明るく全体が写る写真を撮る",caution:"写真だけで種類を確定できません。",medical:false}}
async function ai(){const fd=new FormData();fd.append("image",file);fd.append("mode",mode);const r=await fetch(AI_ENDPOINT+"/analyze",{method:"POST",body:fd});if(!r.ok)throw Error();return r.json()}
function show(x){$("name").textContent=x.name||"判定結果";$("candidate").textContent=x.candidate||"不明";$("riskText").textContent=x.risk||"判定困難";$("action").textContent=x.action||"安全な場所へ移動";$("caution").textContent=x.caution||"写真だけでは確定できません";$("score").textContent=(x.score??50)+"%";$("bar").style.width=(x.score??50)+"%";$("risk").textContent=x.risk||"判定困難";$("risk").className="risk "+(x.risk==="危険"?"danger":"");$("medical").classList.toggle("hidden",!x.medical);$("result").classList.remove("hidden");$("result").scrollIntoView({behavior:"smooth"})}
$("analyze").onclick=async()=>{if(!file){$("status").textContent="まず写真を選んでください。";return}$("status").textContent=AI_ENDPOINT?"AIで画像を確認中…":"デモ判定中…";try{show(AI_ENDPOINT?await ai():demo());$("status").textContent=AI_ENDPOINT?"AI判定を表示しました。":"v0.3デモ判定です。AI接続はREADME参照。"}catch(e){show(demo());$("status").textContent="AI接続に失敗したためデモ判定を表示しました。"}};
$("post").onclick=()=>{const area=$("area").value.trim();if(!area){$("postStatus").textContent="地域を入力してください。";return}const a=JSON.parse(localStorage.getItem("mushinavi_sightings")||"[]");a.push({type:$("stype").value,area,note:$("note").value,at:new Date().toISOString()});localStorage.setItem("mushinavi_sightings",JSON.stringify(a));$("postStatus").textContent="このブラウザに保存しました。";$("area").value="";$("note").value=""};
