const photoInput=document.getElementById("photoInput"),previewWrap=document.getElementById("previewWrap"),preview=document.getElementById("preview"),removePhoto=document.getElementById("removePhoto"),diagnoseBtn=document.getElementById("diagnoseBtn"),diagnoseMsg=document.getElementById("diagnoseMsg"),result=document.getElementById("result");
let selectedType="hachi",photoSelected=false;
document.querySelectorAll(".type-card").forEach(card=>card.addEventListener("click",()=>{selectedType=card.dataset.type;document.querySelectorAll(".type-card").forEach(c=>c.classList.remove("active"));card.classList.add("active");document.getElementById("hachiQuestions").classList.toggle("hidden",selectedType!=="hachi");document.getElementById("madaniQuestions").classList.toggle("hidden",selectedType!=="madani");result.classList.add("hidden");}));
photoInput.addEventListener("change",()=>{const file=photoInput.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){diagnoseMsg.textContent="画像ファイルを選択してください。";return}const r=new FileReader();r.onload=e=>{preview.src=e.target.result;previewWrap.classList.remove("hidden");photoSelected=true;diagnoseMsg.textContent="写真を読み込みました。"};r.readAsDataURL(file)});
removePhoto.addEventListener("click",()=>{photoInput.value="";preview.src="";previewWrap.classList.add("hidden");photoSelected=false;result.classList.add("hidden");diagnoseMsg.textContent=""});
function hachiResult(){const nest=document.getElementById("hNest").value,near=document.getElementById("hNear").value;if(nest==="yes"||near==="yes")return{candidate:"蜂（スズメバチ等を含む可能性）",risk:"危険",cls:"red",action:"近づかず、人やペットを安全な場所へ移動する",caution:"巣や集団がある場合は刺激せず、必要なら専門業者へ相談してください。",extra:"巣をつつく・追い払う・自分で駆除するなど、刺激する行動は避けてください。"};return{candidate:"蜂の可能性",risk:"注意",cls:"orange",action:"安全な距離から確認し、近づかない",caution:"写真だけでは種類を確定できません。巣が見つかった場合は無理に対処しないでください。",extra:"刺される危険があるため、手で払ったり追い回したりしないでください。"}}
function madaniResult(){const attached=document.getElementById("mAttached").value;if(attached==="yes")return{candidate:"マダニの可能性",risk:"要相談",cls:"red",action:"無理に引っ張ったり潰したりせず、医療機関への相談を検討する",caution:"付着しているマダニを自分で無理に除去すると、口器が残るなどの問題が起こる可能性があります。",extra:"発熱などの体調変化がある場合は、マダニに刺された可能性を伝えて医療機関へ相談してください。"};return{candidate:"マダニの可能性",risk:"注意",cls:"orange",action:"素手で触らず、衣服・皮膚を確認する",caution:"写真だけでは確定できません。草むら・森林などの後は身体や衣服を確認してください。",extra:"付着が疑われる場合は無理に取ろうとせず、適切な医療機関への相談を検討してください。"}}
diagnoseBtn.addEventListener("click",()=>{if(!photoSelected){diagnoseMsg.textContent="まず写真を選んでください。";return}let vals=selectedType==="hachi"?["hLocation","hNest","hNear"]:["mLocation","mAttached","mPulled"];if(vals.some(id=>!document.getElementById(id).value)){diagnoseMsg.textContent="3項目すべて選択してください。";return}diagnoseMsg.textContent="確認中…";setTimeout(()=>{const d=selectedType==="hachi"?hachiResult():madaniResult();document.getElementById("resultCandidate").textContent=d.candidate;document.getElementById("resultRisk").textContent=d.risk;document.getElementById("resultAction").textContent=d.action;document.getElementById("resultCaution").textContent=d.caution;const pill=document.getElementById("riskPill");pill.textContent=d.risk;pill.className=`pill ${d.cls}`;document.getElementById("resultTitle").textContent=selectedType==="hachi"?"蜂の確認結果":"マダニの確認結果";const ex=document.getElementById("resultEmergency");ex.textContent=d.extra;ex.classList.remove("hidden");result.classList.remove("hidden");diagnoseMsg.textContent="確認結果を表示しました。";result.scrollIntoView({behavior:"smooth",block:"start"})},500)});
const sightings=JSON.parse(localStorage.getItem("mushinavi_sightings")||"[]");
document.getElementById("postSighting").addEventListener("click",()=>{const type=document.getElementById("sightingType").value,area=document.getElementById("sightingArea").value.trim(),note=document.getElementById("sightingNote").value.trim(),msg=document.getElementById("postMsg");if(!area){msg.textContent="地域を入力してください。";return}sightings.push({type,area,note,createdAt:new Date().toISOString()});localStorage.setItem("mushinavi_sightings",JSON.stringify(sightings));msg.textContent=`「${area}」の${type}情報を保存しました。v0.2ではこのブラウザ内だけに保存されます。`;document.getElementById("sightingArea").value="";document.getElementById("sightingNote").value=""});
document.querySelectorAll(".marker").forEach(m=>m.addEventListener("click",()=>alert(m.title+"\nv0.2のデモ用目撃地点です。")));
